from __future__ import annotations

from getpass import getpass
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ENV_PATH = ROOT / ".env"

DEFAULTS = {
    "LLM_PROVIDER": "deepseek",
    "LLM_BASE_URL": "https://api.deepseek.com",
    "LLM_MODEL": "deepseek-v4-flash",
    "LLM_TIMEOUT_SECONDS": "45",
    "LLM_MAX_TOKENS": "1200",
    "LLM_TEMPERATURE": "0.2",
    "LLM_DEEPSEEK_THINKING": "false",
    "LLM_REASONING_EFFORT": "high",
    "LLM_ENABLE_VISION": "false",
    "LLM_VISION_MODEL": "",
}


def load_env(path: Path) -> dict[str, str]:
    data: dict[str, str] = {}
    if not path.exists():
        return data
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        data[key.strip()] = value.strip()
    return data


def redact(value: str) -> str:
    if not value:
        return "未填写"
    if len(value) <= 10:
        return "****"
    return value[:6] + "****" + value[-4:]


def main() -> None:
    print("EquipMind A1 - DeepSeek 本地配置初始化")
    print("说明：密钥只会写入你本机的 .env 文件，.env 已在 .gitignore 中，不应上传参赛压缩包或代码仓库。")
    old = load_env(ENV_PATH)
    api_key = getpass("请输入 DeepSeek API Key（输入时不显示）：").strip()
    if not api_key:
        api_key = old.get("LLM_API_KEY", "").strip()
    if not api_key:
        raise SystemExit("未填写 API Key，已取消。")
    if not api_key.startswith("sk-") or " " in api_key or "python" in api_key.lower():
        raise SystemExit("输入内容不像 DeepSeek API Key。请粘贴以 sk- 开头的完整密钥，不要粘贴命令。")

    data = {**DEFAULTS, **old}
    data.update({
        "LLM_PROVIDER": "deepseek",
        "LLM_BASE_URL": "https://api.deepseek.com",
        "LLM_API_KEY": api_key,
        "DEEPSEEK_API_KEY": api_key,
        "LLM_MODEL": data.get("LLM_MODEL") or "deepseek-v4-flash",
    })

    lines = [
        "# Auto-generated by scripts/init_deepseek.py",
        "# Do not upload this file. Keep your API key private.",
    ]
    order = [
        "LLM_PROVIDER", "LLM_BASE_URL", "LLM_API_KEY", "DEEPSEEK_API_KEY", "LLM_MODEL",
        "LLM_TIMEOUT_SECONDS", "LLM_MAX_TOKENS", "LLM_TEMPERATURE",
        "LLM_DEEPSEEK_THINKING", "LLM_REASONING_EFFORT",
        "LLM_ENABLE_VISION", "LLM_VISION_MODEL",
    ]
    for key in order:
        lines.append(f"{key}={data.get(key, '')}")
    ENV_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"已写入：{ENV_PATH}")
    print(f"当前 Provider: {data['LLM_PROVIDER']}")
    print(f"当前模型: {data['LLM_MODEL']}")
    print(f"API Key: {redact(api_key)}")
    print("下一步：python scripts/test_llm.py")


if __name__ == "__main__":
    main()
